import "./globals.css";
import Navbar from "@/components/navbar";
import { Providers } from "./providers";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Navbar></Navbar>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
